name: Lint App

on: 
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  PY_VERSION: 3.13

jobs:
  lint:
    name: Lint files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ env.PY_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PY_VERSION }}
    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        source .venv/bin/activate
        pylint $(git ls-files '*.py')
